### ISSUE TITLE
No solution found trying to install buildah

### ISSUE THREAD

**Issue by maya-r** [rmohr/bazeldnf#19]
With the following reproducing script:

````sh
cat << EOF > repo.yaml
repositories:
- arch: x86_64
  baseurl: http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/
  name: centos/stream9-baseos-x86_64
  gpgkey: https://www.stream.centos.org/keys/RPM-GPG-KEY-CentOS-Official
- arch: x86_64
  baseurl: http://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/
  name: centos/stream9-appstream-x86_64
  gpgkey: https://www.stream.centos.org/keys/RPM-GPG-KEY-CentOS-Official
EOF

bazel run //:bazeldnf -- fetch
bazel run //:bazeldnf -- rpmtree --public --name testimage --basesystem centos-stream-release buildah
````

INFO[0004] Loading the Partial weighted MAXSAT problem. 
INFO[0004] Solving the Partial weighted MAXSAT problem. 
INFO[0004] No solution found.                           
Error: no solution found

I can force a solution with `--force-ignore-with-dependencies containers-common` so I suspect this is the problematic package - maybe because new versions are conflicting with old versions of the same package? but I am not sure how to correct bazeldnf for this.

**Comment by rmohr** [comment]
Does it work for stream8?

Thanks for the details.

**Comment by maya-r** [comment]
This fails for stream8 as well

**Comment by maya-r** [comment]
Oops, I tried to check for stream8 but in fact I wasn't. It works using centos stream 8.

**Comment by maya-r** [comment]
CentOS Stream packages have changed such that this problem no longer reproduces, which would make it near impossible to work on the bug. Closing and hoping it won't happen in the future.
